Hue 13/add coefficent history
caspa2289/rocket_thing pull request #7
Opened 2023-04-05 14:54 UTC by Nikita1502

2023-04-05 15:59 UTC, caspa2289 requested changes

2023-04-05 15:59 UTC, caspa2289 commented on src/components/Game/components/GameHistory/GameHistory.module.scss
> +  justify-content: space-between;
Если там будет 2 элемента, они разъедутся в разные концы враппера. Используй свойство gap.

2023-04-05 15:59 UTC, caspa2289 commented on src/components/Game/components/GameHistory/GameHistory.module.scss
> +.zero_cf{
Не используй сокращения, это плохая практика. Через месяц ты сам не вспомнишь, чо это значит.

2023-04-05 15:59 UTC, caspa2289 commented on src/components/Game/components/GameHistory/GameHistory.tsx
> +    val: number
Не используй сокращения. Есть исключения, но их ты поймёшь когда-нибудь потом. Сейчас просто не используй никакие.

2023-04-05 15:59 UTC, caspa2289 commented on src/components/Game/components/GameHistory/GameHistory.tsx
> +export type Tcolor = 'red' | 'white' | 'orange' | 'green'
TColor

2023-04-06 11:23 UTC, Nikita1502 commented on src/components/Game/components/GameHistory/GameHistory.tsx
> +    if (element == 0) {
Не работает свитч

2023-04-06 12:38 UTC, caspa2289 approved these changes

2023-04-06 12:39 UTC, merged